name: 错误反馈(suggestion)
description: 提交与整合包相关的问题与反馈
title: "[反馈]: "
labels:
  - 整合包
  - 问题类型
projects:
  - Journey-of-Forging-Dreams/issus
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        请尽可能简单的概括您遇到的问题！（Please describe the problem you encountered as simply as possible!）

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: 须知
      description: 是否已经检查过了此问题没有重复。(Has this issue been checked to ensure it is not a duplicate?)
      options:
        - label: 确认
          required: true


  - type: checkboxes
    id: code-of-conduct-1
    attributes:
      label: 须知
      description: 是正在使用最新版整合包。(Is it using the latest version of the modpack?)
      options:
        - label: 确认
          required: true

  - type: input
    id: modpack-version
    attributes:
      label: 整合包版本
      description: 您正在使用的整合包版本号。(The version number of the modpack you are using)
      placeholder: 例如：1.0.0
    validations:
      required: true


  - type: dropdown
    id: issue-type
    attributes:
      label: 问题类型
      description: 请选择您提交的问题类型。
      options:
        - BUG
        - 崩溃 (crashes)
        - 优化 (Optimize)
        - 其他 (other)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 详细描述 (Detailed description)
      description: 请详细描述您遇到的问题，包括具体的操作步骤、期望结果和实际结果，最好请提供截图或视频。
      placeholder: 例如：“xxx物品出现了bug...并没有实现xxx功能”
    validations:
      required: true


  - type: textarea
    id: logs
    attributes:
      label: 日志文件 (Log file)
      description: 请提供相关的日志文件内容（若是以文件的形式上传到详细描述部分也是可以的）
      render: shell
    validations:
      required: true
