ServerEvents.recipes(event => {
    // 小型法师挑战
    Gateway.customBuilder("kubejs:small_spell_challenge")
        .size("small")
        .color(0x55aaff)
        .addAttribute("minecraft:generic.max_health", 30)
        .addEffect("minecraft:resistance", 0)
        // 通关奖励
        .addReward("irons_spellbooks:arcane_essence", 3)
        .addReward("irons_spellbooks:oakskin_elixir", 1)
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:ice_spider", 3).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 18)
                entity.addEffect("minecraft:slowness", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 2)
            wave.addEffect("minecraft:speed", 0)
            wave.maxTime(300)
            wave.setupTime(20)
            wave.addReward("irons_spellbooks:arcane_essence", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:ice_spider", 2).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 20)
                entity.addEffect("minecraft:slowness", 1)
            })
            wave.addEntity("irons_spellbooks:apothecarist", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 22)
                entity.addEffect("minecraft:regeneration", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 2)
            wave.addEffect("minecraft:speed", 0)
            wave.maxTime(320)
            wave.setupTime(22)
            wave.addReward("irons_spellbooks:arcane_essence", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:ice_spider", 2).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 22)
                entity.addEffect("minecraft:slowness", 1)
            })
            wave.addEntity("irons_spellbooks:apothecarist", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 24)
                entity.addEffect("minecraft:regeneration", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 3)
            wave.addEffect("minecraft:speed", 0)
            wave.maxTime(340)
            wave.setupTime(25)
            wave.addReward("irons_spellbooks:arcane_essence", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:ice_spider", 2).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 24)
                entity.addEffect("minecraft:slowness", 1)
            })
            wave.addEntity("irons_spellbooks:apothecarist", 2).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 26)
                entity.addEffect("minecraft:regeneration", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 3)
            wave.addEffect("minecraft:speed", 1)
            wave.maxTime(360)
            wave.setupTime(25)
            wave.addReward("irons_spellbooks:arcane_essence", 1)
            wave.addReward("irons_spellbooks:oakskin_elixir", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:ice_spider", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 26)
                entity.addEffect("minecraft:slowness", 1)
            })
            wave.addEntity("irons_spellbooks:apothecarist", 2).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 28)
                entity.addEffect("minecraft:regeneration", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 3)
            wave.addEffect("minecraft:speed", 1)
            wave.maxTime(380)
            wave.setupTime(28)
            wave.addReward("irons_spellbooks:arcane_essence", 2)
            wave.addReward("irons_spellbooks:oakskin_elixir", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:ice_spider", 2).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 28)
                entity.addEffect("minecraft:slowness", 1)
            })
            wave.addEntity("irons_spellbooks:apothecarist", 2).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 30)
                entity.addEffect("minecraft:regeneration", 2)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 4)
            wave.addEffect("minecraft:speed", 1)
            wave.maxTime(400)
            wave.setupTime(30)
            wave.addReward("irons_spellbooks:arcane_essence", 2)
            wave.addReward("irons_spellbooks:oakskin_elixir", 1)
            wave.buildWave()
        })
        .register()

    // 中型法师挑战
    Gateway.customBuilder("kubejs:medium_spell_challenge")
        .size("medium")
        .color(0xffaa00)
        .addAttribute("minecraft:generic.max_health", 50)
        .addEffect("minecraft:strength", 0)
        .addEffect("minecraft:resistance", 0)
        // 通关奖励
        .addReward("irons_spellbooks:cinder_essence", 8)
        .addReward("irons_spellbooks:mithril_scrap", 2)
        .addReward("irons_spellbooks:evasion_elixir", 1)
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:pyromancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 30)
                entity.addEffect("minecraft:fire_resistance", 1)
                entity.addEffect("minecraft:strength", 1)
            })
            wave.addEntity("irons_spellbooks:cryomancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 30)
                entity.addEffect("minecraft:slowness", 0)
                entity.addEffect("minecraft:strength", 0)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 4)
            wave.addEffect("minecraft:speed", 0)
            wave.maxTime(350)
            wave.setupTime(25)
            wave.addReward("irons_spellbooks:cinder_essence", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:pyromancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 32)
                entity.addEffect("minecraft:fire_resistance", 1)
                entity.addEffect("minecraft:strength", 1)
            })
            wave.addEntity("irons_spellbooks:cryomancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 32)
                entity.addEffect("minecraft:slowness", 0)
                entity.addEffect("minecraft:strength", 0)
            })
            wave.addEntity("irons_spellbooks:ice_spider", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 22)
                entity.addEffect("minecraft:slowness", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 4)
            wave.addEffect("minecraft:speed", 0)
            wave.maxTime(370)
            wave.setupTime(25)
            wave.addReward("irons_spellbooks:cinder_essence", 1)
            wave.addReward("irons_spellbooks:mithril_scrap", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:pyromancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 34)
                entity.addEffect("minecraft:fire_resistance", 1)
                entity.addEffect("minecraft:strength", 1)
            })
            wave.addEntity("irons_spellbooks:cryomancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 34)
                entity.addEffect("minecraft:slowness", 0)
                entity.addEffect("minecraft:strength", 0)
            })
            wave.addEntity("irons_spellbooks:apothecarist", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 28)
                entity.addEffect("minecraft:regeneration", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 4)
            wave.addEffect("minecraft:speed", 1)
            wave.maxTime(390)
            wave.setupTime(28)
            wave.addReward("irons_spellbooks:cinder_essence", 1)
            wave.addReward("irons_spellbooks:mithril_scrap", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:pyromancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 36)
                entity.addEffect("minecraft:fire_resistance", 1)
                entity.addEffect("minecraft:strength", 1)
            })
            wave.addEntity("irons_spellbooks:cryomancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 36)
                entity.addEffect("minecraft:slowness", 0)
                entity.addEffect("minecraft:strength", 0)
            })
            wave.addEntity("irons_spellbooks:apothecarist", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 30)
                entity.addEffect("minecraft:regeneration", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 5)
            wave.addEffect("minecraft:speed", 1)
            wave.maxTime(400)
            wave.setupTime(30)
            wave.addReward("irons_spellbooks:cinder_essence", 2)
            wave.addReward("irons_spellbooks:mithril_scrap", 1)
            wave.addReward("irons_spellbooks:evasion_elixir", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:archevoker", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 40)
                entity.addEffect("minecraft:strength", 1)
                entity.addEffect("minecraft:absorption", 1)
            })
            wave.addEntity("irons_spellbooks:pyromancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 35)
                entity.addEffect("minecraft:fire_resistance", 1)
                entity.addEffect("minecraft:strength", 1)
            })
            wave.addEntity("irons_spellbooks:cryomancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 35)
                entity.addEffect("minecraft:slowness", 1)
                entity.addEffect("minecraft:strength", 0)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 5)
            wave.addEffect("minecraft:speed", 1)
            wave.maxTime(450)
            wave.setupTime(35)
            wave.addReward("irons_spellbooks:cinder_essence", 2)
            wave.addReward("irons_spellbooks:mithril_scrap", 2)
            wave.addReward("irons_spellbooks:evasion_elixir", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:archevoker", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 45)
                entity.addEffect("minecraft:strength", 1)
                entity.addEffect("minecraft:absorption", 2)
            })
            wave.addEntity("irons_spellbooks:pyromancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 38)
                entity.addEffect("minecraft:fire_resistance", 1)
                entity.addEffect("minecraft:strength", 1)
            })
            wave.addEntity("irons_spellbooks:cryomancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 38)
                entity.addEffect("minecraft:slowness", 1)
                entity.addEffect("minecraft:strength", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 6)
            wave.addEffect("minecraft:speed", 2)
            wave.maxTime(500)
            wave.setupTime(35)
            wave.addReward("irons_spellbooks:cinder_essence", 2)
            wave.addReward("irons_spellbooks:mithril_scrap", 2)
            wave.addReward("irons_spellbooks:evasion_elixir", 1)
            wave.buildWave()
        })
        .register()

    // 大型法师挑战
    Gateway.customBuilder("kubejs:large_spell_challenge")
        .size("large")
        .color(0xff2255)
        .addAttribute("minecraft:generic.max_health", 80)
        .addEffect("minecraft:strength", 1)
        .addEffect("minecraft:resistance", 0)
        // 通关奖励
        .addReward("irons_spellbooks:arcane_essence", 32)
        .addReward("irons_spellbooks:cinder_essence", 8)
        .addReward("irons_spellbooks:mithril_scrap", 8)
        .addReward("irons_spellbooks:upgrade_orb", 6)
        .addReward("irons_spellbooks:blank_rune", 8)
        .addReward("hazennstuff:runestone_fragments", 4)
        .addReward("irons_spellbooks:greater_oakskin_elixir", 1)
        .addReward("irons_spellbooks:netherward_tincture", 1)
        .addReward("irons_spellbooks:fire_ale", 4)
        .addReward("irons_spellbooks:greater_evasion_elixir", 2)
        .addReward("irons_spellbooks:greater_invisibility_elixir", 2)
        .addReward("irons_spellbooks:invisibility_elixir", 2)
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:necromancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 40)
                entity.addEffect("minecraft:strength", 1)
                entity.addEffect("minecraft:regeneration", 0)
            })
            wave.addEntity("irons_spellbooks:pyromancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 35)
                entity.addEffect("minecraft:fire_resistance", 1)
                entity.addEffect("minecraft:strength", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 5)
            wave.addEffect("minecraft:speed", 0)
            wave.maxTime(380)
            wave.setupTime(25)
            wave.addReward("irons_spellbooks:arcane_essence", 2)
            wave.addReward("irons_spellbooks:cinder_essence", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:necromancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 42)
                entity.addEffect("minecraft:strength", 1)
                entity.addEffect("minecraft:regeneration", 0)
            })
            wave.addEntity("irons_spellbooks:cryomancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 35)
                entity.addEffect("minecraft:slowness", 1)
                entity.addEffect("minecraft:strength", 0)
            })
            wave.addEntity("irons_spellbooks:ice_spider", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 25)
                entity.addEffect("minecraft:slowness", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 5)
            wave.addEffect("minecraft:speed", 0)
            wave.maxTime(400)
            wave.setupTime(28)
            wave.addReward("irons_spellbooks:arcane_essence", 2)
            wave.addReward("irons_spellbooks:cinder_essence", 1)
            wave.addReward("irons_spellbooks:mithril_scrap", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:necromancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 45)
                entity.addEffect("minecraft:strength", 1)
                entity.addEffect("minecraft:regeneration", 0)
            })
            wave.addEntity("irons_spellbooks:pyromancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 38)
                entity.addEffect("minecraft:fire_resistance", 1)
                entity.addEffect("minecraft:strength", 1)
            })
            wave.addEntity("irons_spellbooks:cryomancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 38)
                entity.addEffect("minecraft:slowness", 1)
                entity.addEffect("minecraft:strength", 0)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 6)
            wave.addEffect("minecraft:speed", 1)
            wave.maxTime(430)
            wave.setupTime(30)
            wave.addReward("irons_spellbooks:arcane_essence", 2)
            wave.addReward("irons_spellbooks:cinder_essence", 2)
            wave.addReward("irons_spellbooks:mithril_scrap", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:necromancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 48)
                entity.addEffect("minecraft:strength", 1)
                entity.addEffect("minecraft:regeneration", 1)
            })
            wave.addEntity("irons_spellbooks:archevoker", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 45)
                entity.addEffect("minecraft:strength", 1)
                entity.addEffect("minecraft:absorption", 1)
            })
            wave.addEntity("irons_spellbooks:pyromancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 40)
                entity.addEffect("minecraft:fire_resistance", 1)
                entity.addEffect("minecraft:strength", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 6)
            wave.addEffect("minecraft:speed", 1)
            wave.maxTime(460)
            wave.setupTime(32)
            wave.addReward("irons_spellbooks:arcane_essence", 3)
            wave.addReward("irons_spellbooks:cinder_essence", 2)
            wave.addReward("irons_spellbooks:mithril_scrap", 2)
            wave.addReward("irons_spellbooks:blank_rune", 8)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:necromancer", 2).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 50)
                entity.addEffect("minecraft:strength", 2)
                entity.addEffect("minecraft:regeneration", 1)
            })
            wave.addEntity("irons_spellbooks:archevoker", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 48)
                entity.addEffect("minecraft:strength", 1)
                entity.addEffect("minecraft:absorption", 1)
            })
            wave.addEntity("irons_spellbooks:cryomancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 40)
                entity.addEffect("minecraft:slowness", 1)
                entity.addEffect("minecraft:strength", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 7)
            wave.addEffect("minecraft:speed", 1)
            wave.maxTime(500)
            wave.setupTime(35)
            wave.addReward("irons_spellbooks:arcane_essence", 3)
            wave.addReward("irons_spellbooks:cinder_essence", 2)
            wave.addReward("irons_spellbooks:mithril_scrap", 2)
            wave.addReward("irons_spellbooks:upgrade_orb", 1)
            wave.addReward("hazennstuff:runestone_fragments", 2)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:necromancer", 2).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 55)
                entity.addEffect("minecraft:strength", 2)
                entity.addEffect("minecraft:regeneration", 1)
            })
            wave.addEntity("irons_spellbooks:archevoker", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 52)
                entity.addEffect("minecraft:strength", 2)
                entity.addEffect("minecraft:absorption", 2)
            })
            wave.addEntity("irons_spellbooks:pyromancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 42)
                entity.addEffect("minecraft:fire_resistance", 1)
                entity.addEffect("minecraft:strength", 1)
            })
            wave.addEntity("irons_spellbooks:cryomancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 42)
                entity.addEffect("minecraft:slowness", 1)
                entity.addEffect("minecraft:strength", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 8)
            wave.addEffect("minecraft:speed", 2)
            wave.maxTime(550)
            wave.setupTime(40)
            wave.addReward("irons_spellbooks:arcane_essence", 32)
            wave.addReward("irons_spellbooks:cinder_essence", 8)
            wave.addReward("irons_spellbooks:mithril_scrap", 3)
            wave.addReward("irons_spellbooks:upgrade_orb", 1)
            wave.addReward("irons_spellbooks:blank_rune", 8)
            wave.addReward("hazennstuff:runestone_fragments", 3)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("irons_spellbooks:dead_king", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 100)
                entity.addEffect("minecraft:strength", 3)
                entity.addEffect("minecraft:resistance", 1)
                entity.addEffect("minecraft:regeneration", 0)
            })
            wave.addEntity("irons_spellbooks:necromancer", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 55)
                entity.addEffect("minecraft:strength", 2)
                entity.addEffect("minecraft:regeneration", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 9)
            wave.addEffect("minecraft:speed", 2)
            wave.maxTime(700)
            wave.setupTime(50)
            wave.addReward("irons_spellbooks:arcane_essence", 64)
            wave.addReward("irons_spellbooks:cinder_essence", 8)
            wave.addReward("irons_spellbooks:mithril_scrap", 12)
            wave.addReward("irons_spellbooks:upgrade_orb", 6)
            wave.addReward("irons_spellbooks:blank_rune", 8)
            wave.addReward("hazennstuff:runestone_fragments", 32)
            wave.buildWave()
        })
        .register()

    Gateway.customBuilder("kubejs:small_ocean_challenge")
        .size("small")
        .color(0x00ccff)
        .addAttribute("minecraft:generic.max_health", 30)
        .addEffect("minecraft:resistance", 0)
        // 通关奖励
        .addReward("minecraft:prismarine_shard", 8)
        .addReward("minecraft:prismarine_crystals", 4)
        .addReward("minecraft:iron_ingot", 4)
        .addWave(wave => {
            wave.addEntity("cataclysm:deepling", 3).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 18)
                entity.addEffect("minecraft:strength", 0)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 2)
            wave.addEffect("minecraft:speed", 0)
            wave.maxTime(300)
            wave.setupTime(20)
            wave.addReward("minecraft:prismarine_shard", 2)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("cataclysm:deepling", 2).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 20)
                entity.addEffect("minecraft:strength", 0)
            })
            wave.addEntity("cataclysm:urchinkin", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 22)
                entity.addEffect("minecraft:strength", 0)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 2)
            wave.addEffect("minecraft:speed", 0)
            wave.maxTime(320)
            wave.setupTime(22)
            wave.addReward("minecraft:prismarine_shard", 2)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("cataclysm:deepling", 2).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 22)
                entity.addEffect("minecraft:strength", 1)
            })
            wave.addEntity("cataclysm:urchinkin", 2).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 24)
                entity.addEffect("minecraft:strength", 0)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 3)
            wave.addEffect("minecraft:speed", 0)
            wave.maxTime(340)
            wave.setupTime(25)
            wave.addReward("minecraft:prismarine_shard", 2)
            wave.addReward("minecraft:prismarine_crystals", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("cataclysm:deepling_brute", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 26)
                entity.addEffect("minecraft:strength", 1)
                entity.addEffect("minecraft:resistance", 0)
            })
            wave.addEntity("cataclysm:deepling", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 24)
                entity.addEffect("minecraft:strength", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 3)
            wave.addEffect("minecraft:speed", 1)
            wave.maxTime(360)
            wave.setupTime(25)
            wave.addReward("minecraft:prismarine_shard", 3)
            wave.addReward("minecraft:prismarine_crystals", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("cataclysm:deepling_brute", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 28)
                entity.addEffect("minecraft:strength", 1)
                entity.addEffect("minecraft:resistance", 0)
            })
            wave.addEntity("cataclysm:deepling_priest", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 26)
                entity.addEffect("minecraft:regeneration", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 3)
            wave.addEffect("minecraft:speed", 1)
            wave.maxTime(380)
            wave.setupTime(28)
            wave.addReward("minecraft:prismarine_shard", 3)
            wave.addReward("minecraft:prismarine_crystals", 2)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("cataclysm:deepling_brute", 2).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 30)
                entity.addEffect("minecraft:strength", 2)
                entity.addEffect("minecraft:resistance", 0)
            })
            wave.addEntity("cataclysm:urchinkin", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 28)
                entity.addEffect("minecraft:strength", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 4)
            wave.addEffect("minecraft:speed", 1)
            wave.maxTime(400)
            wave.setupTime(30)
            wave.addReward("minecraft:prismarine_shard", 4)
            wave.addReward("minecraft:prismarine_crystals", 2)
            wave.buildWave()
        })
        .register()

    // 中型海洋挑战
    Gateway.customBuilder("kubejs:medium_ocean_challenge")
        .size("medium")
        .color(0x0088ff)
        .addAttribute("minecraft:generic.max_health", 50)
        .addEffect("minecraft:strength", 0)
        .addEffect("minecraft:resistance", 0)
        // 通关奖励
        .addReward("minecraft:prismarine_shard", 12)
        .addReward("minecraft:prismarine_crystals", 6)
        .addReward("minecraft:diamond", 2)
        .addReward("minecraft:heart_of_the_sea", 1)
        .addWave(wave => {
            wave.addEntity("cataclysm:deepling_brute", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 30)
                entity.addEffect("minecraft:strength", 1)
                entity.addEffect("minecraft:resistance", 0)
            })
            wave.addEntity("cataclysm:deepling", 2).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 25)
                entity.addEffect("minecraft:strength", 0)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 4)
            wave.addEffect("minecraft:speed", 0)
            wave.maxTime(350)
            wave.setupTime(25)
            wave.addReward("minecraft:prismarine_shard", 3)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("cataclysm:deepling_brute", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 32)
                entity.addEffect("minecraft:strength", 1)
                entity.addEffect("minecraft:resistance", 0)
            })
            wave.addEntity("cataclysm:urchinkin", 2).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 28)
                entity.addEffect("minecraft:strength", 0)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 4)
            wave.addEffect("minecraft:speed", 0)
            wave.maxTime(370)
            wave.setupTime(25)
            wave.addReward("minecraft:prismarine_shard", 3)
            wave.addReward("minecraft:prismarine_crystals", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("cataclysm:deepling_brute", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 34)
                entity.addEffect("minecraft:strength", 2)
                entity.addEffect("minecraft:resistance", 0)
            })
            wave.addEntity("cataclysm:deepling_priest", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 30)
                entity.addEffect("minecraft:regeneration", 1)
                entity.addEffect("minecraft:strength", 0)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 4)
            wave.addEffect("minecraft:speed", 1)
            wave.maxTime(390)
            wave.setupTime(28)
            wave.addReward("minecraft:prismarine_shard", 3)
            wave.addReward("minecraft:prismarine_crystals", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("cataclysm:deepling_warlock", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 35)
                entity.addEffect("minecraft:strength", 1)
                entity.addEffect("minecraft:resistance", 0)
            })
            wave.addEntity("cataclysm:deepling_brute", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 35)
                entity.addEffect("minecraft:strength", 2)
                entity.addEffect("minecraft:resistance", 0)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 5)
            wave.addEffect("minecraft:speed", 1)
            wave.maxTime(410)
            wave.setupTime(30)
            wave.addReward("minecraft:prismarine_shard", 4)
            wave.addReward("minecraft:prismarine_crystals", 2)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("cataclysm:deepling_warlock", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 38)
                entity.addEffect("minecraft:strength", 1)
                entity.addEffect("minecraft:resistance", 0)
            })
            wave.addEntity("cataclysm:deepling_priest", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 32)
                entity.addEffect("minecraft:regeneration", 2)
                entity.addEffect("minecraft:strength", 0)
            })
            wave.addEntity("cataclysm:urchinkin", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 28)
                entity.addEffect("minecraft:strength", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 5)
            wave.addEffect("minecraft:speed", 1)
            wave.maxTime(430)
            wave.setupTime(30)
            wave.addReward("minecraft:prismarine_shard", 4)
            wave.addReward("minecraft:prismarine_crystals", 2)
            wave.addReward("minecraft:diamond", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            // 小Boss：珊瑚傀儡
            wave.addEntity("cataclysm:coral_golem", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 50)
                entity.addEffect("minecraft:strength", 2)
                entity.addEffect("minecraft:resistance", 1)
            })
            wave.addEntity("cataclysm:deepling_warlock", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 40)
                entity.addEffect("minecraft:strength", 1)
                entity.addEffect("minecraft:resistance", 0)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 6)
            wave.addEffect("minecraft:speed", 2)
            wave.maxTime(500)
            wave.setupTime(35)
            wave.addReward("minecraft:prismarine_shard", 5)
            wave.addReward("minecraft:prismarine_crystals", 3)
            wave.addReward("minecraft:diamond", 1)
            wave.buildWave()
        })
        .register()

    // 大型海洋挑战
    Gateway.customBuilder("kubejs:large_ocean_challenge")
        .size("large")
        .color(0x0044ff)
        .addAttribute("minecraft:generic.max_health", 80)
        .addEffect("minecraft:strength", 1)
        .addEffect("minecraft:resistance", 0)
        // 通关奖励
        .addReward("minecraft:prismarine_shard", 20)
        .addReward("minecraft:prismarine_crystals", 10)
        .addReward("minecraft:diamond", 4)
        .addReward("minecraft:heart_of_the_sea", 2)
        .addReward("minecraft:netherite_scrap", 8)
        .addReward("kubejs:supreme_mana_potion", 1)
        .addReward("kubejs:supreme_healing_potion", 1)
        .addWave(wave => {
            wave.addEntity("cataclysm:coral_golem", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 40)
                entity.addEffect("minecraft:strength", 2)
                entity.addEffect("minecraft:resistance", 0)
            })
            wave.addEntity("cataclysm:deepling_warlock", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 35)
                entity.addEffect("minecraft:strength", 1)
                entity.addEffect("minecraft:resistance", 0)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 5)
            wave.addEffect("minecraft:speed", 0)
            wave.maxTime(380)
            wave.setupTime(25)
            wave.addReward("minecraft:prismarine_shard", 4)
            wave.addReward("minecraft:prismarine_crystals", 2)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("cataclysm:coral_golem", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 42)
                entity.addEffect("minecraft:strength", 2)
                entity.addEffect("minecraft:resistance", 0)
            })
            wave.addEntity("cataclysm:deepling_priest", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 35)
                entity.addEffect("minecraft:regeneration", 2)
            })
            wave.addEntity("cataclysm:deepling_brute", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 32)
                entity.addEffect("minecraft:strength", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 5)
            wave.addEffect("minecraft:speed", 0)
            wave.maxTime(400)
            wave.setupTime(28)
            wave.addReward("minecraft:prismarine_shard", 4)
            wave.addReward("minecraft:prismarine_crystals", 2)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("cataclysm:coral_golem", 2).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 45)
                entity.addEffect("minecraft:strength", 2)
                entity.addEffect("minecraft:resistance", 1)
            })
            wave.addEntity("cataclysm:deepling_warlock", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 38)
                entity.addEffect("minecraft:strength", 1)
                entity.addEffect("minecraft:resistance", 0)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 6)
            wave.addEffect("minecraft:speed", 1)
            wave.maxTime(430)
            wave.setupTime(30)
            wave.addReward("minecraft:prismarine_shard", 5)
            wave.addReward("minecraft:prismarine_crystals", 2)
            wave.addReward("minecraft:diamond", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            // 小Boss：沧溟巡守 (hippocamtus)
            wave.addEntity("cataclysm:hippocamtus", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 55)
                entity.addEffect("minecraft:strength", 2)
                entity.addEffect("minecraft:resistance", 1)
            })
            wave.addEntity("cataclysm:coral_golem", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 45)
                entity.addEffect("minecraft:strength", 2)
                entity.addEffect("minecraft:resistance", 0)
            })
            wave.addEntity("cataclysm:deepling_warlock", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 40)
                entity.addEffect("minecraft:strength", 1)
                entity.addEffect("minecraft:resistance", 0)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 6)
            wave.addEffect("minecraft:speed", 1)
            wave.maxTime(460)
            wave.setupTime(32)
            wave.addReward("minecraft:prismarine_shard", 5)
            wave.addReward("minecraft:prismarine_crystals", 3)
            wave.addReward("minecraft:diamond", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            // 小Boss：巨钳守卫 (clawdian)
            wave.addEntity("cataclysm:clawdian", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 60)
                entity.addEffect("minecraft:strength", 3)
                entity.addEffect("minecraft:resistance", 1)
            })
            wave.addEntity("cataclysm:hippocamtus", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 55)
                entity.addEffect("minecraft:strength", 2)
                entity.addEffect("minecraft:resistance", 1)
            })
            wave.addEntity("cataclysm:coral_golem", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 48)
                entity.addEffect("minecraft:strength", 2)
                entity.addEffect("minecraft:resistance", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 7)
            wave.addEffect("minecraft:speed", 1)
            wave.maxTime(500)
            wave.setupTime(35)
            wave.addReward("minecraft:prismarine_shard", 6)
            wave.addReward("minecraft:prismarine_crystals", 3)
            wave.addReward("minecraft:diamond", 1)
            wave.addReward("minecraft:heart_of_the_sea", 1)
            wave.buildWave()
        })
        .addWave(wave => {
            // 小Boss：珊瑚巨像 (coralssus)
            wave.addEntity("cataclysm:coralssus", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 70)
                entity.addEffect("minecraft:strength", 3)
                entity.addEffect("minecraft:resistance", 2)
            })
            wave.addEntity("cataclysm:clawdian", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 55)
                entity.addEffect("minecraft:strength", 2)
                entity.addEffect("minecraft:resistance", 1)
            })
            wave.addEntity("cataclysm:hippocamtus", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 55)
                entity.addEffect("minecraft:strength", 2)
                entity.addEffect("minecraft:resistance", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 8)
            wave.addEffect("minecraft:speed", 2)
            wave.maxTime(600)
            wave.setupTime(40)
            wave.addReward("minecraft:prismarine_shard", 6)
            wave.addReward("minecraft:prismarine_crystals", 4)
            wave.addReward("minecraft:diamond", 2)
            wave.addReward("minecraft:heart_of_the_sea", 1)
            wave.addReward("minecraft:netherite_scrap", 8)
            wave.buildWave()
        })
        .addWave(wave => {
            wave.addEntity("cataclysm:scylla", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 150)
                entity.addEffect("minecraft:strength", 4)
                entity.addEffect("minecraft:resistance", 2)
                entity.addEffect("minecraft:regeneration", 0)
            })
            wave.addEntity("cataclysm:coralssus", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 70)
                entity.addEffect("minecraft:strength", 3)
                entity.addEffect("minecraft:resistance", 2)
            })
            wave.addEntity("cataclysm:clawdian", 1).modify(entity => {
                entity.addAttribute("minecraft:generic.max_health", 60)
                entity.addEffect("minecraft:strength", 2)
                entity.addEffect("minecraft:resistance", 1)
            })
            wave.addAttribute("minecraft:generic.attack_damage", 10)
            wave.addEffect("minecraft:speed", 2)
            wave.maxTime(800)
            wave.setupTime(50)
            wave.addReward("minecraft:prismarine_shard", 10)
            wave.addReward("minecraft:prismarine_crystals", 5)
            wave.addReward("minecraft:diamond", 4)
            wave.addReward("minecraft:heart_of_the_sea", 3)
            wave.addReward("minecraft:netherite_scrap", 8)
            wave.addReward("kubejs:supreme_mana_potion", 1)
            wave.addReward("kubejs:supreme_healing_potion", 1)
            wave.buildWave()
        })
        .register()
})