#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jan 22 10:21:04 GMT+08:00 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=6
shaderPack=Derivative+Main+d24.4.14.zip
