#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Dec 25 22:02:53 GMT+08:00 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=6
shaderPack=Kappa_v5.3.zip
