#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Aug 11 19:14:34 GMT+08:00 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=6
shaderPack=Solas_Shader_V3.1b.zip
