[Loot]
	#What is the maximum number of items that increase Luck (in loot chests)
	# Default: 10
	# Range: 1 ~ 1024
	maxAddLootItems = 10
	#Loot chests are forbidden to double items with a maximum stack quantity of 1，This will reduce the problem of loot being repelled by a large number of non-stackable items
	notOneItem = false
	#Each Luck value affects how many items are added to the loot table
	# Default: 1
	# Range: 1 ~ 1024
	oneAddItem = 1
