version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "FAST"
leavesCullingAmount = 4
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
azurelib = true
tide = true
samurai_dynasty = true
shineals_prehistoric_expansion = true
farmersdelight = true
terra_curio = true
mysticalagradditions = true
cold_sweat = true
lightmanscurrency = true
endrem = true
silentgems = true
silentgear = true
mysticalagriculture = true
friendsandfoes = true
gravestone = true
reactive = true
biomeswevegone = true
elixirum = true
minecraft = true
irons_spellbooks = true
allthemodium = true
gobber2 = true
irons_jewelry = true
lootr = true
actuallyadditions = true
crystal_chronicles = true
extradelight = true
grimoireofgaia = true
alltheores = true
sophisticatedstorage = true
endermanoverhaul = true
beautify = true
waystones = true
apothic_enchanting = true
fruitsdelight = true
handcrafted = true
ftbquests = true
melter = true
immersiveengineering = true
sophisticatedbackpacks = true
morevillagers = true
toms_storage = true
fargostalismans = true
