# default : false
show_reinforcement_value=true

# default : #00000000
afterimage_color=#00000000

# default : #00000000
shadow_herobrine_color=#00000000

# default : true
play_herobrine_boss_music=true

# default : false
disable_emissive_render_type=false

# default : 20
ore_see_through_range=20

# default : true
enable_ore_see_through=true

# default : 500
herobrine_sky_cloud_speed=500

# default : 4.0
camera_shaking_speed=4.0

# default : 0.025
camera_shaking_strength=0.025

# default : false
disable_world_open_experimental_warning=false

