onCull = true
MaxEntityEntities = 192
qualityModes = "ULTRA"
RenderWeather = "LOW"
FastItemRender = true
RenderDisplayItem = false
blackListedEntities = []
whiteListedEntities = ["terra_entity:tomb_crawler", "terra_entity:giant_worm", "terra_entity:devourer", "terra_entity:eater_of_worlds", "terra_entity:eater_of_worlds_segment", "minecraft:bat", "minecraft:ender_dragon", "twilightforest:hydra", "twilightforest:naga", "twilightforest:snow_queen", "twilightforest:ur_ghast", "cataclysm:ignis", "cataclysm:the_harbinger", "minecraft:blaze", "minecraft:bee", "minecraft:player", "ftboceanmobs:tentacled_horror", "minecraft:arrow", "minecraft:spectral_arrow", "iceandfire:dragon_arrow", "minecraft:firework_rocket", "iceandfire:stymphalian_arrow", "iceandfire:amphithere_arrow", "iceandfire:sea_serpent_arrow", "iceandfire:hydra_arrow", "aquaculture:water_arrow", "twilightforest:seeker_arrow", "twilightforest:ice_arrow", "cataclysm:void_scatter_arrow", "cataclysm:phantom_arrow", "irons_spellbooks:small_magic_arrow", "irons_spellbooks:fire_arrow", "irons_spellbooks:poison_arrow", "irons_spellbooks:ice_spider", "minecraft:tnt", "terra_entity:wall_of_flesh", "terra_entity:wall_of_flesh_eye", "terra_entity:wall_of_flesh_mouth", "terra_entity:chester"]
isAlwaysShowItemCount = true
startTime = 43.338
chatFix = true
onGui = false
GuiRXTX = false
GuiFPS = true
GuiCPU = true
GuiGPU = true
GuiRAM = true
GuiEntityCount = false
GuiPlayerPos = false
GuiServer = false
GuiCameraTarget = false
Mood = false
Particle = true
BlockBreakParticleMode = "NORMAL"
MaxParticleDistance = 134
WhiteListedParticle = []
BlackListedParticle = ["champions:rank", "minecraft:instant_effect", "minecraft:entity_effect"]
FPSMonitor = false
GuiEasyRamMode = false
GuiDisplayRamUsage = false
GuiX = 0
GuiY = 0
EntityRender = true
UseAui = false
DeBug = true
TextBackground = false
TextureAnimatedSprites = true
SoundDevicesMonitor = false
SetParticleMaxAge = true
ParticleMaxAge = 2
GuiViewMode = "TECHNICAL"
EntityCullFov = 242
MinDistance = 6
EntityDistance = 96
TickPerformance = false
