onCull = true
MaxEntityEntities = 128
qualityModes = "NORMAL"
RenderWeather = "NORMAL"
FastItemRender = true
RenderDisplayItem = false
blackListedEntities = []
whiteListedEntities = ["terra_entity:hornet", "terra_entity:man_eater", "terra_entity:snatcher", "iceandfire:lightning_dragon", "iceandfire:hydra", "iceandfire:fire_dragon", "iceandfire:ice_dragon", "minecraft:allay", "ftboceanmobs:rift_weaver", "eternal_starlight:tiny_creteor", "terra_entity:brain_of_cthulhu", "terra_entity:eater_of_world", "terra_entity:cthulhu_eye", "terra_entity:king_slime", "terra_entity:antlion_swarmer", "terra_entity:harpy", "terra_entity:devourer", "terra_entity:decayeder", "terra_entity:tomb_crawler", "terra_entity:undead_viking", "terra_entity:anger_bones", "terra_entity:wall_of_flesh", "terra_entity:dungeon_guardian", "eternal_starlight:creteor", "terra_entity:blood_crawler", "eternal_starlight:crystallized_moth", "terra_entity:flying_fish", "iceandfire:gorgon", "iceandfire:amphithere", "iceandfire:ghost", "terra_entity:giant_antlion", "terra_entity:giant_worm", "terra_entity:bloody_spore", "terra_entity:hell_bat", "terra_entity:queen_bee", "terra_entity:skeletron"]
BlackTagListEntity = []
WhiteTagListEntity = []
isAlwaysShowItemCount = false
startTime = 43.695
Hud = false
HudRXTX = false
HudFPS = false
HudCPU = false
HudGPU = false
HudRAM = false
HudEntityCount = false
HudPlayerPos = false
HudServer = false
HudCameraTarget = false
Mood = true
MaxParticleDistance = 128
WhiteListedParticle = []
BlackListedParticle = []
GuiEasyRamMode = false
GuiDisplayRamUsage = false
GuiX = 0
GuiY = 0
UseAui = false
DeBug = true
TextBackground = false
TextureAnimatedSprites = true
SoundDevicesMonitor = false
SetParticleMaxAge = true
ParticleMaxAge = 2
GuiViewMode = "TECHNICAL"
MinDistance = 5
EntityDistance = 64
TickPerformance = false
ParticlePerformance = true
EntityViewDebug = false
ParticleCountLimit = 16384
BlockBreakParticle = true
AsyncCompute = true
