let fluids = [
    { id: 'abiding_alloy', color: 0x00ffff },
    { id: 'achroous', color: 0x90c1a3 },
    { id: 'adamanite', color: 0xc30f30 },
    { id: 'acril', color: 0xf0d366 },
    { id: 'aero_steel', color: 0x83c9e3 },
    { id: 'aluminum', color: 0xd8d6d8 },
    { id: 'animated_steel', color: 0x3469c1 },
    { id: 'berkelium', color: 0x74888f },
    { id: 'boron', color: 0x547991 },
    { id: 'brass', color: 0xfacc79 },
    { id: 'bronze', color: 0xf9ce7c },
    { id: 'calamatium', color: 0xeea266 },
    { id: 'carbonatite', color: 0x263340 },
    { id: 'celeslar', color: 0x59a293 },
    { id: 'chalyblux', color: 0xf5d1ef },
    { id: 'chromium', color: 0x5a5a5a },
    { id: 'cobalt', color: 0xbcebf7 },
    { id: 'cosmos_aurora', color: 0xffbfab },
    { id: 'dark_cryopla', color: 0x5cdee6 },
    { id: 'echo', color: 0x197487 },
    { id: 'electrum', color: 0xf9ffa8 },
    { id: 'enlighted_gold', color: 0xe4feed },
    { id: 'estalt', color: 0xa67f4e },
    { id: 'europium', color: 0xb499ed },
    { id: 'frigidite', color: 0xb5edf2 },
    { id: 'invar', color: 0xe7ebe5 },
    { id: 'iridium', color: 0xcecece },
    { id: 'isovol', color: 0x3d2756 },
    { id: 'lead', color: 0xadc3ff },
    { id: 'lustful_haze_alloy', color: 0x8f2265 },
    { id: 'luteous', color: 0xf29cad },
    { id: 'magmanite', color: 0xe1bdd8 },
    { id: 'magnesium', color: 0x867777 },
    { id: 'magnetite', color: 0xc2e3d1 },
    { id: 'midnight_abyssal', color: 0x277984 },
    { id: 'mythril', color: 0x62c5a9 },
    { id: 'neptunium', color: 0x61b8a6 },
    { id: 'nickel', color: 0xcdcbb0 },
    { id: 'nlatstone', color: 0xb0e2fa },
    { id: 'osmium', color: 0xe8f6fb },
    { id: 'palladium', color: 0xf4b8ad },
    { id: 'platinum', color: 0xc5f3ff },
    { id: 'plumbumanite', color: 0x4aeeef },
    { id: 'plutonium', color: 0xca84d8 },
    { id: 'polonium', color: 0x6991b4 },
    { id: 'rhexis', color: 0xbd2739 },
    { id: 'rhodium', color: 0xe7e0c9 },
    { id: 'scandium', color: 0xb79c75 },
    { id: 'scepbo', color: 0xeaa016 },
    { id: 'silicon', color: 0xbbc5cd },
    { id: 'silver', color: 0xc9c9c9 },
    { id: 'solimrith', color: 0xbe87bc },
    { id: 'starinium', color: 0xbe1257 },
    { id: 'starlight_mythril', color: 0xff8b78 },
    { id: 'steel', color: 0x9f9f9f },
    { id: 'stellar', color: 0x5ac5a5 },
    { id: 'strontium', color: 0xd48f67 },
    { id: 'tellurium', color: 0xa6e0c1 },
    { id: 'thlanium', color: 0xdfc9e5 },
    { id: 'terraulite', color: 0xa2e02f },
    { id: 'thorium', color: 0xe089ce },
    { id: 'thulium', color: 0x6f4441 },
    { id: 'tin', color: 0xe5ecf4 },
    { id: 'titanium', color: 0xc47e79 },
    { id: 'tungsten', color: 0x93c3a0 },
    { id: 'ultimate', color: 0x4de046 },
    { id: 'unstable_luminescence', color: 0xe6ffff },
    { id: 'uranium', color: 0x76c76a },
    { id: 'vibranite', color: 0x2d6a7d },
    { id: 'viculeam', color: 0xb52773 },
    { id: 'void', color: 0x209897 },
    { id: 'vorant', color: 0xe14579 },
    { id: 'xeproda', color: 0xffd65d },
    { id: 'yttrium', color: 0xffecb7 },
    { id: 'zapolgium', color: 0xce772f },
    { id: 'zinc', color: 0xbed9d0 },
    { id: 'zirconium', color: 0x746e57 },
    { id: 'xelkive', color: 0xf7ffaf },
    { id: 'lunium_nova', color: 0xccfce2 },
    { id: 'gobber2', color: 0x67b1e5 },
    { id: 'gobber2_nether', color: 0xaf3d6a },
    { id: 'gobber2_end', color: 0x95f3b5 },

];

for (let i = 0; i < fluids.length; i++) {
    let fluid = fluids[i % fluids.length];
    StartupEvents.registry('fluid', event => {
        event.create(fluid.id, 'thick')
            .tint(fluid.color)
    });
}
