StartupEvents.registry("item", event => {
    event.create('bluestar')
        .food(food => {
            food.nutrition(8)
                .saturation(0.2)
        })
        .tag('kubejs:bluestar')
        .texture('kubejs:item/food/blue_star')
    event.create('raw_manflesh')
        .food(food => {
            food.nutrition(6)
                .saturation(0.2)
                .eatSeconds(1.5)
                .effect('minecraft:hunger', 60, 0, 0.2)
        })
        .tag('kubejs:foods/manflesh')
        .tag('kubejs:foods/manflesh/raw_manflesh')
        .texture('kubejs:item/food/raw_manflesh')
    event.create('cooked_manflesh')
        .food(food => {
            food.nutrition(8)
                .saturation(0.4)
                .eatSeconds(1.3)
                .effect('minecraft:hunger', 80, 0, 0.4)
                .alwaysEdible()
        })
        .tag('kubejs:foods/manflesh')
        .tag('kubejs:foods/manflesh/cooked_manflesh')
        .texture('kubejs:item/food/cooked_manflesh')
})