StartupEvents.registry('item', event => {
    event.create('spell_resistance_helmet', 'helmet')
        .fireResistant(true)
        .unstackable()
        .maxDamage(600)
        .rarity('epic')
        .texture('kubejs:item/armor/spell_resistance_helmet')
        .translationKey("item.kubejs.spell_resistance_helmet")
    event.create('spell_resistance_chestplate', 'chestplate')
        .fireResistant(true)
        .unstackable()
        .maxDamage(1200)
        .rarity('epic')
        .texture('kubejs:item/armor/spell_resistance_chestplate')
        .translationKey("item.kubejs.spell_resistance_chestplate")
    event.create('spell_resistance_leggings', 'leggings')
        .fireResistant(true)
        .unstackable()
        .maxDamage(1100)
        .rarity('epic')
        .texture('kubejs:item/armor/spell_resistance_leggings')
        .translationKey("item.kubejs.spell_resistance_leggings")
    event.create('spell_resistance_boots', 'boots')
        .fireResistant(true)
        .unstackable()
        .maxDamage(700)
        .rarity('epic')
        .texture('kubejs:item/armor/spell_resistance_boots')
        .translationKey("item.kubejs.spell_resistance_boots")
    event.create('azure_dawnbreaker_helmet', 'helmet')
        .fireResistant(true)
        .unstackable()
        .maxDamage(600)
        .rarity('epic')
        .translationKey("item.kubejs.azure_dawnbreaker_helmet")
        .texture('kubejs:item/armor/azure_dawnbreaker_helmet')
        .material('kubejs:azure_dawnbreaker');
    event.create('azure_dawnbreaker_chestplate', 'chestplate')
        .fireResistant(true)
        .unstackable()
        .maxDamage(1200)
        .rarity('epic')
        .texture('kubejs:item/armor/azure_dawnbreaker_chestplate')
        .translationKey("item.kubejs.azure_dawnbreaker_chestplate")
        .material('kubejs:azure_dawnbreaker');
    event.create('azure_dawnbreaker_leggings', 'leggings')
        .fireResistant(true)
        .unstackable()
        .maxDamage(1100)
        .rarity('epic')
        .texture('kubejs:item/armor/azure_dawnbreaker_leggings')
        .translationKey("item.kubejs.azure_dawnbreaker_leggings")
        .material('kubejs:azure_dawnbreaker');
    event.create('azure_dawnbreaker_boots', 'boots')
        .fireResistant(true)
        .unstackable()
        .maxDamage(700)
        .rarity('epic')
        .texture('kubejs:item/armor/azure_dawnbreaker_boots')
        .translationKey("item.kubejs.azure_dawnbreaker_boots")
        .material('kubejs:azure_dawnbreaker');
})
StartupEvents.registry('armor_material', event => {
    event.create('kubejs:azure_dawnbreaker');
});